<SelectAppScreen>:
    name: 'select_app'
    BoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 10

        Label:
            text: "Choose an App to Lock"

        Button:
            text: "App1"
            on_release: root.select_app('App1')

        Button:
            text: "App2"
            on_release: root.select_app('App2')

        Button:
            text: "App3"
            on_release: root.select_app('App3')